# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getGLPKVersion <- function() {
    .Call(`_cobrar_getGLPKVersion`)
}

initProb <- function(name) {
    .Call(`_cobrar_initProb`, name)
}

setObjDir <- function(xp, dir) {
    .Call(`_cobrar_setObjDir`, xp, dir)
}

addColsLP <- function(xp, ncols) {
    .Call(`_cobrar_addColsLP`, xp, ncols)
}

addRowsLP <- function(xp, nrows) {
    .Call(`_cobrar_addRowsLP`, xp, nrows)
}

loadMatrixLP <- function(xp, ne, ia, ja, ra) {
    .Call(`_cobrar_loadMatrixLP`, xp, ne, ia, ja, ra)
}

setColsBndsObjCoefsLP <- function(xp, j, type, lb, ub, obj_coef) {
    .Call(`_cobrar_setColsBndsObjCoefsLP`, xp, j, type, lb, ub, obj_coef)
}

setColsKindLP <- function(xp, j, kind) {
    .Call(`_cobrar_setColsKindLP`, xp, j, kind)
}

setRowsBndsLP <- function(xp, i, type, lb, ub) {
    .Call(`_cobrar_setRowsBndsLP`, xp, i, type, lb, ub)
}

getSolStatLP <- function(xp) {
    .Call(`_cobrar_getSolStatLP`, xp)
}

getColsPrimalLP <- function(xp) {
    .Call(`_cobrar_getColsPrimalLP`, xp)
}

solveSimplex <- function(xp) {
    .Call(`_cobrar_solveSimplex`, xp)
}

solveSimplexExact <- function(xp) {
    .Call(`_cobrar_solveSimplexExact`, xp)
}

getObjVal <- function(xp) {
    .Call(`_cobrar_getObjVal`, xp)
}

solveInterior <- function(xp) {
    .Call(`_cobrar_solveInterior`, xp)
}

getObjValIpt <- function(xp) {
    .Call(`_cobrar_getObjValIpt`, xp)
}

solveMIP <- function(xp) {
    .Call(`_cobrar_solveMIP`, xp)
}

mipObjVal <- function(xp) {
    .Call(`_cobrar_mipObjVal`, xp)
}

getColsDualIptLP <- function(xp) {
    .Call(`_cobrar_getColsDualIptLP`, xp)
}

getColsDualLP <- function(xp) {
    .Call(`_cobrar_getColsDualLP`, xp)
}

setMatRowLP <- function(xp, i, len, ind, val) {
    .Call(`_cobrar_setMatRowLP`, xp, i, len, ind, val)
}

getNumRowsLP <- function(xp) {
    .Call(`_cobrar_getNumRowsLP`, xp)
}

fvaLP <- function(xp, ind) {
    .Call(`_cobrar_fvaLP`, xp, ind)
}

getSBMLVersion <- function() {
    .Call(`_cobrar_getSBMLVersion`)
}

readSBMLfile <- function(file_path) {
    .Call(`_cobrar_readSBMLfile`, file_path)
}

getModelObj <- function(sbml_document_ptr) {
    .Call(`_cobrar_getModelObj`, sbml_document_ptr)
}

getModelId <- function(model_ptr) {
    .Call(`_cobrar_getModelId`, model_ptr)
}

getModelName <- function(model_ptr) {
    .Call(`_cobrar_getModelName`, model_ptr)
}

getModelCompartments <- function(model_ptr) {
    .Call(`_cobrar_getModelCompartments`, model_ptr)
}

getStoichiometricMatrix <- function(model_ptr) {
    .Call(`_cobrar_getStoichiometricMatrix`, model_ptr)
}

getModelAnnotation <- function(model_ptr) {
    .Call(`_cobrar_getModelAnnotation`, model_ptr)
}

getModelNotes <- function(model_ptr) {
    .Call(`_cobrar_getModelNotes`, model_ptr)
}

getObjectiveFunction <- function(model_ptr) {
    .Call(`_cobrar_getObjectiveFunction`, model_ptr)
}

getSubsystems <- function(model_ptr) {
    .Call(`_cobrar_getSubsystems`, model_ptr)
}

getReactionIds <- function(model_ptr) {
    .Call(`_cobrar_getReactionIds`, model_ptr)
}

getReactionNames <- function(model_ptr) {
    .Call(`_cobrar_getReactionNames`, model_ptr)
}

getReactionCompartment <- function(model_ptr) {
    .Call(`_cobrar_getReactionCompartment`, model_ptr)
}

getReactionAnnotation <- function(model_ptr) {
    .Call(`_cobrar_getReactionAnnotation`, model_ptr)
}

getReactionFluxBounds <- function(model_ptr) {
    .Call(`_cobrar_getReactionFluxBounds`, model_ptr)
}

getMetaboliteIds <- function(model_ptr) {
    .Call(`_cobrar_getMetaboliteIds`, model_ptr)
}

getMetaboliteNames <- function(model_ptr) {
    .Call(`_cobrar_getMetaboliteNames`, model_ptr)
}

getMetaboliteAnnotation <- function(model_ptr) {
    .Call(`_cobrar_getMetaboliteAnnotation`, model_ptr)
}

getMetaboliteCompartments <- function(model_ptr) {
    .Call(`_cobrar_getMetaboliteCompartments`, model_ptr)
}

getGeneProducts <- function(model_ptr) {
    .Call(`_cobrar_getGeneProducts`, model_ptr)
}

getGPRs <- function(model_ptr) {
    .Call(`_cobrar_getGPRs`, model_ptr)
}

