# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

readSBMLfile <- function(file_path) {
    .Call(`_cobrar_readSBMLfile`, file_path)
}

getModelObj <- function(sbml_document_ptr) {
    .Call(`_cobrar_getModelObj`, sbml_document_ptr)
}

getStoichiometricMatrix <- function(model_ptr) {
    .Call(`_cobrar_getStoichiometricMatrix`, model_ptr)
}

getReactionIds <- function(model_ptr) {
    .Call(`_cobrar_getReactionIds`, model_ptr)
}

getReactionNames <- function(model_ptr) {
    .Call(`_cobrar_getReactionNames`, model_ptr)
}

getReactionFluxBounds <- function(model_ptr) {
    .Call(`_cobrar_getReactionFluxBounds`, model_ptr)
}

