# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getGLPKVersion <- function() {
    .Call(`_cobrar_getGLPKVersion`)
}

getSBMLVersion <- function() {
    .Call(`_cobrar_getSBMLVersion`)
}

readSBMLfile <- function(file_path) {
    .Call(`_cobrar_readSBMLfile`, file_path)
}

getModelObj <- function(sbml_document_ptr) {
    .Call(`_cobrar_getModelObj`, sbml_document_ptr)
}

getModelId <- function(model_ptr) {
    .Call(`_cobrar_getModelId`, model_ptr)
}

getModelName <- function(model_ptr) {
    .Call(`_cobrar_getModelName`, model_ptr)
}

getModelCompartments <- function(model_ptr) {
    .Call(`_cobrar_getModelCompartments`, model_ptr)
}

getStoichiometricMatrix <- function(model_ptr) {
    .Call(`_cobrar_getStoichiometricMatrix`, model_ptr)
}

getModelAnnotation <- function(model_ptr) {
    .Call(`_cobrar_getModelAnnotation`, model_ptr)
}

getModelNotes <- function(model_ptr) {
    .Call(`_cobrar_getModelNotes`, model_ptr)
}

getObjectiveFunction <- function(model_ptr) {
    .Call(`_cobrar_getObjectiveFunction`, model_ptr)
}

getSubsystems <- function(model_ptr) {
    .Call(`_cobrar_getSubsystems`, model_ptr)
}

getReactionIds <- function(model_ptr) {
    .Call(`_cobrar_getReactionIds`, model_ptr)
}

getReactionNames <- function(model_ptr) {
    .Call(`_cobrar_getReactionNames`, model_ptr)
}

getReactionAnnotation <- function(model_ptr) {
    .Call(`_cobrar_getReactionAnnotation`, model_ptr)
}

getReactionFluxBounds <- function(model_ptr) {
    .Call(`_cobrar_getReactionFluxBounds`, model_ptr)
}

getMetaboliteIds <- function(model_ptr) {
    .Call(`_cobrar_getMetaboliteIds`, model_ptr)
}

getMetaboliteNames <- function(model_ptr) {
    .Call(`_cobrar_getMetaboliteNames`, model_ptr)
}

getMetaboliteAnnotation <- function(model_ptr) {
    .Call(`_cobrar_getMetaboliteAnnotation`, model_ptr)
}

